# Generated by Django 4.0.6 on 2022-07-30 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_branches_branch'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Branch',
            new_name='Branches',
        ),
    ]
