# Generated by Django 4.0.6 on 2022-07-31 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_newuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewUser',
        ),
    ]
